/* A guided adviser review: source comparison -> final check -> lenders. */
(function(global){
  'use strict';
  const P=global.MandatePitch,R=global.MandateReview,V=global.MandatePitchViews,e=P.escape;
  const state=new Map();
  global.MandateResetPitchFlow=()=>state.clear();
  const current=()=>global.MandateCreatedDeals?.[global.MandateActiveDealId]||global.MandateWorkingDeals?.[global.MandateActiveDealId];
  const view=()=>{const id=global.MandateActiveDealId;if(!state.has(id))state.set(id,{pane:current()?.sampleSubmission&&R.isFinal(current())?'results':'inputs',filter:'all'});return state.get(id);};
  function element(html){const t=document.createElement('template');t.innerHTML=html;return t.content.firstElementChild;}
  function formatted(path,value){if(!R.present(value))return 'Not supplied';if(Array.isArray(value))return value.join(', ');if(typeof value==='number')return path==='funding.termMonths'?value+' months':P.money(value);return value;}
  const filename=name=>name.replace(/\.csv$/i,'').replace(/^(kowhai|southern)-/i,'').replace(/-/g,' ');
  function sources(group){return `<details class="source-list"><summary>${group.sources.length} ${group.sources.length===1?'source':'sources'}${group.period?' · '+e(group.period):''}</summary>${group.sources.map(s=>`<span>${e(s.name)}</span>`).join('')}</details>`;}
  function choice(row,group){let difference='';if(typeof row.current==='number'&&typeof group.value==='number'&&row.current!==group.value){const delta=group.value-row.current;difference=`<small class="source-delta">${e(formatted(row.path,Math.abs(delta)))} ${delta>0?'higher':'lower'} than entered</small>`;}return `<div class="source-option"><strong>${e(formatted(row.path,group.value))}</strong>${difference}${sources(group)}${!row.confirmed&&!row.same?`<button class="review-choice" data-review-field="${row.path}" data-review-choice="${e(group.sources[0].id)}">Use this CSV value</button>`:''}</div>`;}
  function reviewRows(deal){const progress=R.progress(deal);const filter=view().filter;const items=progress.items.filter(r=>filter==='all'||(filter==='differences'?r.different&&!r.confirmed:!r.confirmed)).sort((a,b)=>Number(b.different&&!b.confirmed)-Number(a.different&&!a.confirmed));const matching=progress.items.filter(r=>r.same&&!r.confirmed);
    return `<section class="review-section" aria-labelledby="review-title"><div class="review-title-row"><div><h2 id="review-title">Compare and confirm</h2><p>Your deal details are on the left. Values read from the CSVs are on the right.</p></div><span class="review-count" role="status">${progress.confirmed} of ${progress.items.length} fields confirmed</span></div><div class="review-tools"><div class="review-filters" aria-label="Filter fields"><button data-review-filter="all" aria-pressed="${filter==='all'}">All fields</button><button data-review-filter="differences" aria-pressed="${filter==='differences'}">Differences <b>${progress.items.filter(r=>r.different&&!r.confirmed).length}</b></button><button data-review-filter="pending" aria-pressed="${filter==='pending'}">To review <b>${progress.pending.length}</b></button></div>${matching.length?`<button class="review-choice" data-confirm-matches>Confirm ${matching.length} matching fields</button>`:''}</div><div class="review-grid-head"><span>Field</span><span>Current deal details</span><span>Extracted from CSV</span><span>Your decision</span></div><div class="review-grid">${items.map(row=>`<section class="review-row ${row.confirmed?'is-confirmed':row.different?'has-difference':''}" aria-label="Review ${e(row.label)}"><div class="review-field"><h3>${e(row.label)}</h3><span class="review-badge ${row.confirmed?'confirmed':row.different?'different':''}">${row.confirmed?'Confirmed':row.different?'Difference':row.same?'Values match':'Needs review'}</span></div><div class="review-entered"><small class="mobile-column-label">Current deal details</small><strong>${e(formatted(row.path,row.current))}</strong>${!row.confirmed&&!row.same?`<button class="review-choice quiet" data-review-field="${row.path}" data-review-choice="current" ${row.required&&!R.present(row.current)?'disabled':''}>${R.present(row.current)?'Keep this value':'Leave as unknown'}</button>`:''}</div><div class="review-extracted"><small class="mobile-column-label">Extracted from CSV</small>${row.groups.map(g=>choice(row,g)).join('')||'<span class="source-empty">No CSV value supplied</span>'}</div><div class="review-decision">${row.confirmed?`<strong>${e(formatted(row.path,row.current))}</strong><button class="review-choice quiet" data-reopen-field="${row.path}">Change decision</button>`:row.same?`<button class="review-choice primary" data-review-field="${row.path}" data-review-choice="${e(row.groups[0].sources[0].id)}">Confirm match</button>`:'<span>Choose the value to carry into the summary.</span>'}</div></section>`).join('')||'<p class="review-empty">No fields left in this view. Select All fields to see your decisions.</p>'}</div></section>`;
  }
  function historyReview(deal,data){if(!deal.pitchHistory?.length)return '';return `<section class="review-history"><div class="review-title-row"><div><h2>Check the financial history</h2><p>These annual figures will appear in each lender’s PDF.</p></div></div><div class="pitch-table-wrap">${V.financialTable(data)}</div><label class="review-checkbox"><input type="checkbox" data-history-reviewed ${R.progress(deal).historyNeeded?'':'checked'}>I have checked these periods and figures against the source accounts.</label></section>`;}
  function footer(deal){const p=R.progress(deal),remaining=p.pending.length+(p.historyNeeded?1:0);return `<div class="review-complete-bar"><div><strong>${p.complete?'Ready for the final check':remaining+' '+(remaining===1?'item':'items')+' left to review'}</strong><p>${p.complete?'Your choices are saved. Review them together before continuing.':'Resolve differences and confirm the values you want in the summary.'}</p></div><button class="button button-dark" data-flow-done ${p.complete?'':'disabled'}>Done · review summary</button></div>`;}
  function finalCheck(deal,data){const rows=R.rows(deal);return `<section class="final-check"><div class="flow-heading"><h2>One final check.</h2><p>These are the exact values you chose. Confirm the summary before viewing potential lenders.</p></div><div class="confirmation-ledger"><div class="confirmation-ledger-head"><h3>Confirmed deal information</h3><button class="review-choice" data-flow-pane="inputs">Back to review</button></div><dl>${rows.map(row=>`<div><dt>${e(row.label)}</dt><dd>${e(formatted(row.path,row.current))}<small>${e(sourceDecision(deal,row))}</small></dd></div>`).join('')}</dl></div>${data.history.length?`<section class="final-history"><h3>Confirmed annual accounts</h3><div class="pitch-table-wrap">${V.financialTable(data)}</div></section>`:''}<div class="final-summary"><label for="finalSummaryText">Broker’s summary</label><p>You can refine the wording below. The confirmed figures remain listed above.</p><textarea id="finalSummaryText" rows="7" maxlength="6000">${e(data.summary)}</textarea></div><details class="final-open-items"><summary>${data.warnings.length} remaining information ${data.warnings.length===1?'item':'items'}</summary><ul>${data.warnings.map(w=>`<li>${e(w)}</li>`).join('')||'<li>No missing headline fields or expected documents.</li>'}</ul><p>These items stay visible in the report.</p></details><label class="review-checkbox final-ack"><input type="checkbox" id="finalAcknowledgement">I have checked the chosen values, financial history and summary, including any missing information.</label><div class="review-complete-bar"><div><strong>Confirm, then explore lenders</strong><p>Editing the deal or adding files will require a new final check.</p></div><button class="button button-dark" data-final-confirm disabled>Confirm & view lenders</button></div><p id="confirmationError" role="alert"></p></section>`;}
  function sourceDecision(deal,row){const record=deal.review?.fields?.[row.path];const ids=record?.sourceIds||[];return ids.length?deal.documents.filter(d=>ids.includes(d.id)).map(d=>d.name).join(', '):R.present(row.current)?'Entered value confirmed by adviser':'Acknowledged as not supplied';}
  function lenderCards(data){return `${data.deal.sampleSubmission?`<section class="desk-sample-summary"><h2>Reviewed company summary</h2><p>${e(data.summary)}</p>${V.metrics(data)}<p class="pitch-footnote">Preloaded fictional review · Figures from the bundled FY2025 accounts. Missing documents remain listed in the report.</p></section>`:''}<section class="lender-results"><div class="flow-heading"><div><h2>Potential lenders</h2><p>Your confirmed deal, compared with five fictional lender profiles.</p></div><button class="review-choice" data-flow-pane="confirm">Review confirmed summary</button></div><div class="fit-explainer"><strong>How fit is calculated</strong><span>Aligned criteria ÷ all 7 criteria. Unknowns remain in the total. This is criteria alignment, not an approval probability.</span></div><div class="lender-box-grid">${data.lenders.map(l=>`<article class="lender-box"><header><span class="lender-box-initial" aria-hidden="true">${e(l.name.split(' ').map(w=>w[0]).slice(0,2).join(''))}</span><div><h3>${e(l.name)}</h3><p>Fictional private credit fund</p></div><div class="lender-fit"><strong>${l.fit}%</strong><span>criteria fit</span></div></header><dl><div><dt>Funding range</dt><dd>${e(P.money(+l.mandate.min_deal_size))} – ${e(P.money(+l.mandate.max_deal_size))}</dd></div><div><dt>Term</dt><dd>${e(l.mandate.min_term_months)}–${e(l.mandate.max_term_months)} months</dd></div></dl><div class="fit-breakdown"><span>${l.aligned} aligned</span><span>${l.gaps} outside criteria</span><span>${l.checks.filter(c=>c.outcome==='check').length} to check</span></div><details class="lender-box-details"><summary>View criteria comparison</summary>${V.checks(l)}<p class="pitch-footnote">Mandate effective ${e(l.mandate.effective_from)}. Target return ${e(l.mandate.target_return_min_pct)}–${e(l.mandate.target_return_max_pct)}% is example context, not a quoted rate.</p></details><footer><button class="review-choice" data-lender-preview="${e(l.id)}">Preview report</button><button class="button button-dark" data-lender-pdf="${e(l.id)}">Download lender PDF</button></footer></article>`).join('')}</div><section class="confirmed-overview"><h2>Company financial overview</h2>${V.metrics(data)}${V.charts(data)}</section></section>`;}
  function scopedData(data,id){const lender=data.lenders.find(l=>l.id===id);if(!lender)throw Error('Select a lender to prepare its report.');return {...data,lenders:[lender],recipient:lender.name};}
  function reportView(data,id){const selected=scopedData(data,id);return `<div class="pitch-report-toolbar"><div><button class="review-choice" data-flow-pane="results">Back to lenders</button><h2>Report for ${e(selected.recipient)}</h2><p>Confirmed borrower information, financial history and this lender’s criteria.</p></div><div><button class="button-outline" data-flow-print>Print / Save as PDF</button><button class="button button-dark" data-lender-pdf="${e(id)}">Download lender PDF</button></div></div>${V.report(selected)}`;}
  function sampleLinks(deal){if(deal.sampleSubmission)return '<p class="flow-samples">Preloaded fictional documents are shown below. No local CSV was uploaded for this sample.</p>';if(!/^(southern manufacturing demo ltd|kowhai contracting ltd)$/i.test(deal.company.name))return '<p class="flow-samples">Use Start Southern demo on Overview to follow the bundled CSV walkthrough.</p>';const southern=/southern manufacturing/i.test(deal.company.name);const samples=southern?[['Company & request','pitch/southern-company-overview.csv'],['Management accounts','pitch/southern-management-accounts.csv'],['Financial history','pitch/southern-financial-history.csv']]:[['Company overview','borrower-documents/kowhai-company-overview.csv'],['Management accounts','borrower-documents/kowhai-management-accounts.csv'],['Accountant summary · discrepancy','borrower-documents/kowhai-accountant-summary.csv'],['Equipment quote','borrower-documents/kowhai-equipment-quote.csv'],['Funding request','borrower-documents/kowhai-funding-request.csv'],['Financial history','pitch/kowhai-financial-history.csv']];return `<details class="flow-samples"><summary>Download ${southern?'Southern Manufacturing':'Kowhai'} sample CSVs</summary><p>Choose up to five files at a time. Add the history CSV in a second upload if needed.</p>${samples.map(([label,path])=>`<a download href="synthetic-data/${path}">${label}</a>`).join('')}</details>`;}
  const base=global.renderDeal;
  global.renderDeal=function(){
    global.MandateActiveDealId ||= selectedDeal;base();const deal=current();if(!deal)return;
    const s=view(),progress=R.progress(deal),approved=R.isFinal(deal);
    if((s.pane==='results'||s.pane==='report')&&!approved)s.pane=progress.complete?'confirm':'inputs';
    if(s.pane==='confirm'&&!progress.complete)s.pane='inputs';
    const data=P.analyze(deal),root=document.getElementById('appContent');
    const overview=root.querySelector('.overview-facts')?.closest('.detail-card'),docCard=root.querySelector('.document-upload-area')?.closest('.detail-card');
    const area=docCard?.querySelector('.document-upload-area');
    document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page==='deals'));
    root.querySelector('.detail-actions')?.remove();root.querySelector('.detail-layout')?.remove();root.querySelector('.app-disclaimer')?.remove();
    const count=document.querySelector('.nav-count');if(count)count.textContent=String(Object.keys(deals).length);
    const app=element(`<div class="pitch-workspace flow-workspace"><nav class="pitch-steps" aria-label="Deal preparation"><button data-flow-pane="inputs" aria-current="${s.pane==='inputs'?'step':'false'}">1 <span>Review files</span></button><button data-flow-pane="confirm" aria-current="${s.pane==='confirm'?'step':'false'}" ${progress.complete?'':'disabled'}>2 <span>Final check</span></button><button data-flow-pane="results" aria-current="${s.pane==='results'||s.pane==='report'?'step':'false'}" ${approved?'':'disabled'}>3 <span>Potential lenders</span></button></nav><p class="flow-session">Synthetic demo · Changes stay in this browser session</p><section id="pitch-inputs" class="pitch-pane" ${s.pane==='inputs'?'':'hidden'}><div class="flow-heading"><div><h2>Review your deal information</h2><p>Upload the CSVs, then choose which values should appear in the broker’s summary.</p></div></div><details class="flow-deal-details"><summary>View or edit entered deal details</summary><div class="flow-overview-host"></div></details><div class="flow-upload-host"></div><div class="flow-review-host">${reviewRows(deal)}${historyReview(deal,data)}${footer(deal)}</div></section><section id="pitch-confirm" class="pitch-pane" ${s.pane==='confirm'?'':'hidden'}>${finalCheck(deal,data)}</section><section id="pitch-results" class="pitch-pane" ${s.pane==='results'?'':'hidden'}>${approved?lenderCards(data):''}</section><section id="pitch-report" class="pitch-pane" ${s.pane==='report'?'':'hidden'}>${approved&&s.recipient?reportView(data,s.recipient):''}</section></div>`);
    root.append(app);
    if(overview)app.querySelector('.flow-overview-host').append(overview);
    if(area){area.querySelector('#extractedFacts')?.remove();area.querySelector('.sample-document-links')?.remove();area.querySelector('.document-drop-zone span').textContent='Choose up to 5 CSVs at a time · 1 MB per file';const files=area.querySelector('#uploadedDocumentList');if(files&&deal.documents.some(d=>d.sourceType==='local_file')){const wrap=element('<details class=flow-file-register><summary>'+deal.documents.filter(d=>d.sourceType==='local_file').length+' CSV files read · view source register</summary></details>');files.before(wrap);wrap.append(files);}app.querySelector('.flow-upload-host').append(area);area.insertAdjacentHTML('beforeend',sampleLinks(deal));}
    document.getElementById('crumbTitle').textContent=s.pane==='inputs'?'Review files':s.pane==='confirm'?'Final check':'Potential lenders';
  };
  function go(pane){const d=current(),p=R.progress(d);if(pane==='confirm'&&!p.complete)return global.notify('Confirm the remaining fields first.');if((pane==='results'||pane==='report')&&!R.isFinal(d))return global.notify('Complete the final check before viewing lenders.');view().pane=pane;global.renderDeal();document.querySelector('.pitch-steps')?.scrollIntoView({block:'start'});}
  function download(id,button){const deal=current();if(!R.isFinal(deal))return go('confirm');const label=button.textContent;button.disabled=true;button.textContent='Preparing PDF…';try{const data=scopedData(P.analyze(deal),id),blob=global.MandatePitchPDF(data),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=('Mandate-'+deal.company.name+'-'+data.recipient).replace(/[^a-z0-9-]/gi,'-')+'.pdf';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);global.notify('Report prepared for '+data.recipient);}catch(error){global.notify('PDF could not be created. Open Preview report and use Print / Save as PDF.');console.error(error);}finally{button.disabled=false;button.textContent=label;}}
  document.addEventListener('click',function(event){const t=event.target.closest('button');if(!t)return;
    if(t.dataset.flowPane)go(t.dataset.flowPane);
    if(t.dataset.reviewFilter){view().filter=t.dataset.reviewFilter;global.renderDeal();document.getElementById('review-title')?.scrollIntoView({block:'start'});}
    if(t.hasAttribute('data-confirm-matches')){global.MandateSourceReview.ensureCandidates(current());R.rows(current()).filter(r=>r.same&&!r.confirmed).forEach(r=>global.MandateSourceReview.resolveField(r.path,r.groups[0].sources[0].id,false));global.renderDeal();}
    if(t.dataset.reopenField){current().review.fields[t.dataset.reopenField].status='needs_review';global.renderDeal();}
    if(t.hasAttribute('data-flow-done')){const d=current();if(!R.progress(d).complete)return;const generated=global.MandateDealAnalysis.analyzeDeal(d,[]).summary.text;if(d.pitchSummary?.basedOn!==R.signature(d))d.pitchSummary={text:generated,basedOn:R.signature(d)};go('confirm');}
    if(t.hasAttribute('data-final-confirm')){try{if(!document.getElementById('finalAcknowledgement').checked)return;R.approve(current(),document.getElementById('finalSummaryText').value);view().pane='results';global.renderDeal();document.querySelector('.pitch-steps')?.scrollIntoView({block:'start'});}catch(error){document.getElementById('confirmationError').textContent=error.message;}}
    if(t.dataset.lenderPreview){view().recipient=t.dataset.lenderPreview;go('report');}
    if(t.dataset.lenderPdf)download(t.dataset.lenderPdf,t);
    if(t.hasAttribute('data-flow-print')){document.body.classList.add('pitch-print');window.print();document.body.classList.remove('pitch-print');}
  });
  document.addEventListener('change',function(event){if(event.target.hasAttribute('data-history-reviewed')){current().pitchHistoryReviewed=event.target.checked?JSON.stringify(current().pitchHistory):null;global.renderDeal();}if(event.target.id==='finalAcknowledgement')document.querySelector('[data-final-confirm]').disabled=!event.target.checked;});
  document.addEventListener('input',function(event){if(event.target.id==='finalSummaryText'){current().pitchSummary={text:event.target.value,basedOn:R.signature(current())};document.getElementById('finalAcknowledgement').checked=false;document.querySelector('[data-final-confirm]').disabled=true;}});
  window.addEventListener('beforeprint',()=>{if(document.querySelector('#pitch-report:not([hidden])'))document.body.classList.add('pitch-print');});
  window.addEventListener('afterprint',()=>document.body.classList.remove('pitch-print'));
})(window);

