/* Five fictional lenders from Tyler's reference-table CSVs. */
window.MandatePitchLenders = [
  {
    "id": "CP-ABC-PRIVATE-CREDIT",
    "name": "ABC Private Credit",
    "mandate": {
      "mandate_id": "MAN-ABC-001",
      "provider_id": "CP-ABC-PRIVATE-CREDIT",
      "min_deal_size": "5000000",
      "max_deal_size": "15000000",
      "currency": "NZD",
      "sectors": "Manufacturing;industrial",
      "excluded_sectors": "",
      "target_return_min_pct": "10",
      "target_return_max_pct": "16",
      "min_term_months": "12",
      "max_term_months": "60",
      "max_leverage": "3.5",
      "min_ebitda": "1000000",
      "accepted_security": "GSA;plant and equipment",
      "financing_purposes": "Acquisition;refinance;growth capital",
      "available_capital": "",
      "deployment_deadline": "",
      "appetite_level": "High",
      "effective_from": "2026-01-01",
      "effective_to": "",
      "source_note": "Fictional criteria for testing; not researched real terms",
      "synthetic": "true"
    }
  },
  {
    "id": "CP-SOUTHERN-CAPITAL",
    "name": "Southern Capital",
    "mandate": {
      "mandate_id": "MAN-SOUTHERN-001",
      "provider_id": "CP-SOUTHERN-CAPITAL",
      "min_deal_size": "3000000",
      "max_deal_size": "12000000",
      "currency": "NZD",
      "sectors": "Manufacturing;business services",
      "excluded_sectors": "",
      "target_return_min_pct": "11",
      "target_return_max_pct": "18",
      "min_term_months": "12",
      "max_term_months": "48",
      "max_leverage": "4.0",
      "min_ebitda": "750000",
      "accepted_security": "GSA;commercial property;plant and equipment",
      "financing_purposes": "Acquisition;refinance;growth capital",
      "available_capital": "",
      "deployment_deadline": "",
      "appetite_level": "Medium",
      "effective_from": "2026-01-01",
      "effective_to": "",
      "source_note": "Fictional criteria for testing; not researched real terms",
      "synthetic": "true"
    }
  },
  {
    "id": "CP-HARBOUR-CREDIT",
    "name": "Harbour Credit",
    "mandate": {
      "mandate_id": "MAN-HARBOUR-CREDIT-001",
      "provider_id": "CP-HARBOUR-CREDIT",
      "min_deal_size": "1000000",
      "max_deal_size": "10000000",
      "currency": "NZD",
      "sectors": "Manufacturing;healthcare;food",
      "excluded_sectors": "",
      "target_return_min_pct": "12",
      "target_return_max_pct": "20",
      "min_term_months": "6",
      "max_term_months": "36",
      "max_leverage": "5.0",
      "min_ebitda": "500000",
      "accepted_security": "GSA;receivables;inventory",
      "financing_purposes": "Working capital;acquisition;refinance",
      "available_capital": "",
      "deployment_deadline": "",
      "appetite_level": "Medium",
      "effective_from": "2026-01-01",
      "effective_to": "",
      "source_note": "Fictional criteria for testing; not researched real terms",
      "synthetic": "true"
    }
  },
  {
    "id": "CP-PACIFIC-CAPITAL",
    "name": "Pacific Capital",
    "mandate": {
      "mandate_id": "MAN-PACIFIC-001",
      "provider_id": "CP-PACIFIC-CAPITAL",
      "min_deal_size": "2000000",
      "max_deal_size": "9000000",
      "currency": "NZD",
      "sectors": "Manufacturing;construction;agriculture",
      "excluded_sectors": "",
      "target_return_min_pct": "10",
      "target_return_max_pct": "17",
      "min_term_months": "12",
      "max_term_months": "60",
      "max_leverage": "4.5",
      "min_ebitda": "500000",
      "accepted_security": "Property;GSA;plant and equipment",
      "financing_purposes": "Acquisition;capex;growth capital",
      "available_capital": "",
      "deployment_deadline": "",
      "appetite_level": "High",
      "effective_from": "2026-01-01",
      "effective_to": "",
      "source_note": "Fictional criteria for testing; not researched real terms",
      "synthetic": "true"
    }
  },
  {
    "id": "CP-KAURI-PRIVATE-CREDIT",
    "name": "Kauri Private Credit",
    "mandate": {
      "mandate_id": "MAN-KAURI-PRIVATE-001",
      "provider_id": "CP-KAURI-PRIVATE-CREDIT",
      "min_deal_size": "1000000",
      "max_deal_size": "8000000",
      "currency": "NZD",
      "sectors": "Manufacturing;business services",
      "excluded_sectors": "",
      "target_return_min_pct": "10",
      "target_return_max_pct": "15",
      "min_term_months": "12",
      "max_term_months": "48",
      "max_leverage": "4.0",
      "min_ebitda": "400000",
      "accepted_security": "Commercial property;GSA",
      "financing_purposes": "Acquisition;refinance;working capital",
      "available_capital": "",
      "deployment_deadline": "",
      "appetite_level": "Low",
      "effective_from": "2026-01-01",
      "effective_to": "",
      "source_note": "Fictional criteria for testing; not researched real terms",
      "synthetic": "true"
    }
  }
];
