/* Pitch presentation, layered over the existing intake and source-review flow. */
(function(global){
  'use strict';
  const P=global.MandatePitch, e=P.escape, money=P.money;
  const labels={align:'Aligns',gap:'Outside criteria',check:'Needs checking'};
  function checks(lender){return `<div class="pitch-table-wrap"><table class="pitch-table"><thead><tr><th>Criterion</th><th>Lender requirement</th><th>This deal</th><th>Comparison</th></tr></thead><tbody>${lender.checks.map(c=>`<tr><th scope="row">${e(c.label)}</th><td>${e(c.criterion)}</td><td>${e(c.dealValue)}</td><td><span class="pitch-status ${c.outcome}">${labels[c.outcome]}</span></td></tr>`).join('')}</tbody></table></div>`;}
  function lenderDetail(lender){return `<div class="pitch-detail-heading"><div><h3>${e(lender.name)}</h3><p>Fictional private credit fund · mandate effective ${e(lender.mandate.effective_from)}</p></div><span class="pitch-status ${lender.gaps?'gap':'align'}">${lender.aligned} of ${lender.checks.length} criteria align</span></div>${checks(lender)}<p class="pitch-footnote">Security overlap means at least one recorded security type matches; confirm ranking and valuation. Target return ${e(lender.mandate.target_return_min_pct)}–${e(lender.mandate.target_return_max_pct)}% is fictional mandate context, not a quoted interest rate.</p>`;}
  function chart(data,key,title){
    const periods=data.history.filter(p=>Number.isFinite(p[key]));
    if(!periods.length)return `<figure class="pitch-chart"><figcaption>${title}</figcaption><p class="pitch-empty">Upload the financial history CSV to plot annual ${({revenue:'revenue',ebitda:'EBITDA',operatingCash:'operating cash flow',netProfit:'net profit'})[key]||key}. No historical figures are assumed.</p></figure>`;
    const min=Math.min(0,...periods.map(p=>p[key])),max=Math.max(1,...periods.map(p=>p[key])),span=max-min;
    const y=v=>155-(v-min)/span*120,zero=y(0),width=350/periods.length;
    return `<figure class="pitch-chart"><figcaption>${title}<small>Annual actuals · NZD millions</small></figcaption><svg viewBox="0 0 420 205" role="img" aria-label="${e(title+': '+periods.map(p=>p.end.slice(0,4)+' '+money(p[key])).join('; '))}"><line x1="36" y1="${zero}" x2="403" y2="${zero}" stroke="currentColor" opacity=".3"/>${[min,max].map(n=>`<text x="2" y="${y(n)+4}" class="pitch-axis">${(n/1e6).toFixed(1)}</text>`).join('')}${periods.map((p,i)=>{const x=49+i*width,h=Math.max(1,Math.abs(y(p[key])-zero));return `<rect x="${x}" y="${Math.min(zero,y(p[key]))}" width="${Math.min(60,width-16)}" height="${h}" rx="3" class="pitch-bar ${key}"/><text x="${x+Math.min(60,width-16)/2}" y="${p[key]>=0?y(p[key])-10:zero+15}" text-anchor="middle" class="pitch-bar-label">${(p[key]/1e6).toFixed(2)}</text><text x="${x+Math.min(60,width-16)/2}" y="182" text-anchor="middle" class="pitch-axis">FY${p.end.slice(0,4)}</text>`;}).join('')}</svg></figure>`;
  }
  function charts(data){return `<div class="pitch-chart-grid">${chart(data,'revenue','Revenue trajectory')}${chart(data,'ebitda','Operating earnings')}${data.history.some(p=>p.operatingCash!=null)?chart(data,'operatingCash','Operating cash flow'):''}${data.history.some(p=>p.netProfit!=null)?chart(data,'netProfit','Net profit after tax'):''}</div>`;}
  function financialTable(data){
    if(!data.history.length)return '';
    const metrics=[['Revenue','revenue'],['Gross profit','grossProfit'],['EBITDA','ebitda'],['Net profit after tax','netProfit'],['Operating cash flow','operatingCash'],['Interest expense','interest'],['Total assets','assets'],['Total liabilities','liabilities'],['Shareholders equity','equity']].filter(([,key])=>data.history.some(p=>p[key]!=null));
    return `<table class="pitch-table annual-accounts"><caption>Annual actuals · NZD · standalone borrower</caption><thead><tr><th>Financial statement item</th>${data.history.map(p=>`<th>${e(p.end)}</th>`).join('')}</tr></thead><tbody>${metrics.map(([label,key])=>`<tr><th scope="row">${label}</th>${data.history.map(p=>`<td>${money(p[key])}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">EBITDA margin</th>${data.history.map(p=>`<td>${p.revenue>0?(p.ebitda/p.revenue*100).toFixed(1)+'%':'Not available'}</td>`).join('')}</tr></tbody></table>`;
  }
  function metrics(data){return `<dl class="pitch-metrics">${[['Funding requested',money(data.amount)],['Annual revenue',money(data.revenue)],['EBITDA',money(data.ebitda)],['EBITDA margin',data.margin==null?'Not available':data.margin.toFixed(1)+'%']].map(([label,v])=>`<div><dt>${label}</dt><dd>${e(v)}</dd></div>`).join('')}</dl>`;}
  function report(data){
    return `<article class="pitch-report"><header class="pitch-report-head"><span class="pitch-wordmark"><img class="brand-logo brand-logo-light" src="assets/brand/mandate-lockup.svg" alt="Mandate" width="214" height="48"><img class="brand-logo brand-logo-reverse" src="assets/brand/mandate-lockup-reverse.svg" alt="Mandate" width="214" height="48"></span><span>${data.deal.sampleSubmission?'Preloaded sample review':data.reviewed?'Summary reviewed':'Draft for adviser review'} · Synthetic pitch demo</span></header><h1>${e(P.value(data.deal,'company.name')||'Company name needs review')}</h1><p class="pitch-report-subtitle">Funding information memorandum · ${e(new Date(data.generatedAt).toLocaleDateString('en-NZ'))}</p>${data.recipient?`<p class="report-recipient">Prepared for ${e(data.recipient)}</p>`:""}${metrics(data)}<h2>Executive summary</h2><p class="pitch-narrative">${e(data.summary)}</p><h2>Funding request</h2><p>${e(P.value(data.deal,'funding.purpose')||'Purpose needs review')}. Requested term: ${e(P.value(data.deal,'funding.termMonths')||'Not confirmed')} months. Proposed security: ${e((P.value(data.deal,'funding.security')||[]).join(', ')||'Not confirmed')}.</p><h2>Financial performance</h2>${charts(data)}<div class="pitch-table-wrap">${financialTable(data)}</div><p class="pitch-footnote">${data.deal.sampleSubmission?"Only FY2025 is supplied in the bundled sample accounts. Earlier years and other statements are not assumed.":"History comes from the uploaded annual accounts."} Headline figures come from the reviewed deal fields. EBITDA margin = EBITDA ÷ revenue. Acquisition target results and pro forma combined earnings are excluded.</p><h2>Information to confirm</h2><ul>${[...data.warnings,...data.informationRequests].map(w=>`<li>${e(w)}</li>`).join('')}</ul><h2>Source register</h2><ul>${data.deal.documents.filter(d=>d.status==='provided').map(d=>`<li>${e(d.name)} · ${d.sourceType==='local_file'?'read locally from uploaded CSV':'bundled synthetic sample'}</li>`).join('')||'<li>Manual deal entry; no CSV files uploaded.</li>'}</ul>${data.financialSources.length?`<p class="pitch-footnote">${data.financialSources.map(s=>e(s.status+' | '+s.field+': '+money(s.value)+'; period '+(s.period||'not supplied')+'; '+s.file)).join('<br>')}</p>`:''}<h2>Illustrative lender comparison</h2><p>Criteria alignment is a starting point for adviser enquiry. Lender profiles are fictional.</p>${data.lenders.map(l=>`<section class="pitch-report-lender">${lenderDetail(l)}</section>`).join('')}<footer>${e(global.MandateAI?.provenance(data.deal)||'Prepared using local calculations and a reviewable template.')} Synthetic information only; not a credit decision, offer or approval prediction.</footer></article>`;
  }
  global.MandatePitchViews={checks,lenderDetail,chart,charts,financialTable,metrics,report};
})(window);




