/* Distinct dashboard, deal register and relationship directory. */
(function(global){
  'use strict';
  const P=global.MandatePitch,R=global.MandateReview,V=global.MandatePitchViews,e=P.escape;
  const labels={draft:'Draft',adviser_review:'Adviser review',ready_to_send:'Ready to send',sent_to_lender:'Sent to lender',more_information_needed:'More information needed',decision_received:'Outcome recorded'};
  let dealQuery='',dealFilter='all',lenderQuery='';
  function seed(){for(const record of global.MandateWorkspaceSamples.build()){
    global.MandateWorkingDeals[record.id]=record;
    Object.assign(deals[record.id],{name:record.company.name,workflowStage:record.workflow.stage,stage:2});
  }}
  const reset=global.MandateResetWorkflow;
  global.MandateResetWorkflow=function(){reset();seed();global.MandateResetPitchFlow();dealQuery='';dealFilter='all';lenderQuery='';};
  seed();
  const records=()=>Object.keys(deals).map(id=>global.MandateCreatedDeals[id]||global.MandateWorkingDeals[id]).filter(Boolean);
  const stage=d=>d.workflow?.stage||'draft';
  const name=l=>global.MandatePitchLenders.find(x=>x.id===l)?.name||'Not selected';
  function next(d){if(!R.isFinal(d))return 'Review and confirm deal information';const missing=d.documents.find(x=>x.status==='missing');if(missing)return 'Add '+missing.name.toLowerCase();if(stage(d)==='decision_received')return 'Review the recorded outcome';return d.sampleSubmission?.next||'Review lender criteria and prepare a report';}
  function pill(d){return `<span class="desk-status ${stage(d)==='more_information_needed'?'attention':''}">${e(labels[stage(d)]||'Draft')}</span>`;}
  function heading(title,copy,action=true){return `<div class="desk-heading"><div><h1>${title}</h1><p>${copy}</p></div>${action?'<button class="button button-dark" id="newDeal">New deal</button>':''}</div>`;}
  const foot='<p class="desk-footnote">Fictional workspace · Submission and relationship records are simulated. No lender is contacted. Refresh clears session changes.</p>';
  function dealRows(list){return list.map(d=>`<tr><th scope="row"><button class="desk-deal-link" data-desk-deal="${e(d.id)}">${e(d.company.name)}</button><small>${e(d.company.industry)} · ${e(d.company.location)}</small></th><td class="desk-number">${e(P.money(d.funding.amount))}</td><td>${pill(d)}</td><td>${e(next(d))}</td></tr>`).join('');}
  function table(list){return `<div class="desk-table-scroll"><table class="desk-table"><thead><tr><th>Company</th><th>Funding request</th><th>Stage</th><th>Next step</th></tr></thead><tbody>${dealRows(list)}</tbody></table></div>`;}
  function dashboard(){const list=records(),attention=list.filter(d=>!R.isFinal(d)||d.documents.some(x=>x.status==='missing')),sent=list.filter(d=>['sent_to_lender','more_information_needed'].includes(stage(d)));crumbTitle.textContent='Overview';
    appContent.innerHTML=`<div class="pitch-workspace desk-workspace">${heading('Welcome back, Ollie.','Track active deals, outstanding information and your next conversations.')}<dl class="desk-metrics"><div><dt>Active deals</dt><dd>${list.length}</dd><small>${P.money(list.reduce((sum,d)=>sum+d.funding.amount,0))} requested</small></div><div><dt>Needs attention</dt><dd>${attention.length}</dd><small>Review or documents outstanding</small></div><div><dt>With lenders</dt><dd>${sent.length}</dd><small>Simulated submission records</small></div></dl><div class="desk-dashboard"><section class="desk-panel"><div class="desk-section-head"><h2>Deal pipeline</h2><button class="review-choice" data-desk-page="deals">View all deals</button></div>${table(list.slice(0,4))}</section><section class="desk-panel"><h2>Next steps</h2><ul class="desk-tasks">${list.slice(0,4).map(d=>`<li><button data-desk-deal="${e(d.id)}"><strong>${e(next(d))}</strong><span>${e(d.company.name)}</span></button></li>`).join('')}</ul></section><section class="desk-panel"><h2>Recent activity</h2><ul class="desk-activity">${list.flatMap(d=>(d.workflow?.activity||[]).map(a=>({...a,company:d.company.name}))).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,5).map(a=>`<li><strong>${e(a.title)}</strong><span>${e(a.company)}</span><p>${e(a.detail)}</p></li>`).join('')||'<li>No activity yet.</li>'}</ul></section><section class="desk-demo"><img src="assets/brand/mandate-symbol.svg" alt="" width="42" height="42"><h2>Walk through a new deal.</h2><p>Use Southern Manufacturing Demo Ltd to demonstrate the $8m acquisition request, CSV review and lender reports.</p><button class="button button-dark" data-start-pitch>Start Southern demo</button><small>Creates a draft after you review and save the form.</small></section></div>${foot}</div>`;
    updateCount();
  }
  function updateCount(){document.querySelector('.nav-count').textContent=String(records().length);}
  function filteredDeals(){return records().filter(d=>(dealFilter==='all'||(dealFilter==='attention'?!R.isFinal(d)||d.documents.some(x=>x.status==='missing'):['sent_to_lender','more_information_needed'].includes(stage(d))))&&[d.company.name,d.company.industry,d.company.location].join(' ').toLowerCase().includes(dealQuery.toLowerCase()));}
  function dealResults(){const list=filteredDeals();return list.length?table(list):'<p class="desk-empty">No deals match. Try another company or select All deals.</p>';}
  function register(){crumbTitle.textContent='Deals';appContent.innerHTML=`<div class="pitch-workspace desk-workspace">${heading('Current deals','Open a deal to review its information, submission record and lender reports.')}<div class="desk-tools"><label>Search deals<input type="search" id="deskDealSearch" placeholder="Company, industry or location" value="${e(dealQuery)}"></label><div class="review-filters" aria-label="Filter deals">${[['all','All deals'],['attention','Needs attention'],['sent','With lenders']].map(([id,label])=>`<button data-desk-filter="${id}" aria-pressed="${dealFilter===id}">${label}</button>`).join('')}</div></div><section class="desk-panel" id="deskDealResults" aria-label="Current deals">${dealResults()}</section>${foot}</div>`;updateCount();}
  function lenderResults(){const list=global.MandatePitchLenders.filter(l=>[l.name,l.mandate.sectors,l.mandate.financing_purposes].join(' ').toLowerCase().includes(lenderQuery.toLowerCase()));return list.map(l=>{const m=l.mandate,linked=records().filter(d=>d.sampleSubmission?.lender===l.id);return `<article class="desk-lender"><header><span class="lender-box-initial">${e(l.name.split(' ').slice(0,2).map(x=>x[0]).join(''))}</span><div><h2>${e(l.name)}</h2><p>Private credit fund · Demo relationship</p></div><span class="desk-status">${linked.length} linked ${linked.length===1?'deal':'deals'}</span></header><dl><div><dt>Funding range</dt><dd>${P.money(+m.min_deal_size)} – ${P.money(+m.max_deal_size)}</dd></div><div><dt>Term</dt><dd>${e(m.min_term_months)}–${e(m.max_term_months)} months</dd></div><div><dt>Sectors</dt><dd>${e(m.sectors.replaceAll(';',', '))}</dd></div><div><dt>Security</dt><dd>${e(m.accepted_security.replaceAll(';',', '))}</dd></div></dl><details><summary>Relationship & lending information</summary><dl><div><dt>Funding purposes</dt><dd>${e(m.financing_purposes.replaceAll(';',', '))}</dd></div><div><dt>Minimum EBITDA</dt><dd>${P.money(+m.min_ebitda)}</dd></div><div><dt>Maximum leverage</dt><dd>${e(m.max_leverage)}× · basis to verify</dd></div><div><dt>Recorded appetite</dt><dd>${e(m.appetite_level||'Not supplied')} · example only</dd></div><div><dt>Mandate effective</dt><dd>${e(m.effective_from)}</dd></div><div><dt>Contact details</dt><dd>Not supplied in the sample data</dd></div></dl><p>Target return ${e(m.target_return_min_pct)}–${e(m.target_return_max_pct)}% is example mandate context, not a quoted rate. Confirm current appetite and terms directly.</p>${linked.length?`<div class="desk-linked">${linked.map(d=>`<button class="review-choice" data-desk-deal="${e(d.id)}">Open ${e(d.company.name)}</button>`).join('')}</div>`:'<p>No deal activity recorded with this lender.</p>'}</details></article>`;}).join('')||'<p class="desk-empty">No lenders match your search.</p>';}
  function directory(){crumbTitle.textContent='Lenders';appContent.innerHTML=`<div class="pitch-workspace desk-workspace">${heading('Your lender network','Lending preferences and relationship information in one place.',false)}<p class="desk-directory-note">${global.MandatePitchLenders.length} fictional lenders · These demonstrate working relationships; no live connection or outreach is enabled.</p><div class="desk-tools"><label>Search lenders<input type="search" id="deskLenderSearch" placeholder="Lender, sector or purpose" value="${e(lenderQuery)}"></label></div><div class="desk-directory" id="deskLenderResults">${lenderResults()}</div>${foot}</div>`;}
  global.renderOverview=dashboard;global.renderDeals=register;global.renderLenders=directory;
  const render=global.renderDeal;
  global.renderDeal=function(){render();const d=global.MandateCreatedDeals[global.MandateActiveDealId]||global.MandateWorkingDeals[global.MandateActiveDealId];if(!d)return;
    const root=document.querySelector('.flow-workspace');if(!root)return;document.querySelectorAll('.nav-item').forEach(n=>n.setAttribute('aria-current',n.dataset.page==='deals'?'page':'false'));
    const panel=document.createElement('section');panel.className='desk-submission';panel.innerHTML=`<div><strong>${e(labels[stage(d)]||'Draft')}${d.sampleSubmission?' · simulated record':''}</strong><p>${d.sampleSubmission?e(name(d.sampleSubmission.lender))+': '+e(d.sampleSubmission.note)+' No actual lender communication was sent.':'Record your next step locally. This demo does not send to lenders.'}</p></div><label>Deal stage<select id="workflowStageSelect">${Object.entries(labels).map(([key,label])=>`<option value="${key}" ${key===stage(d)?'selected':''}>${label}</option>`).join('')}</select></label><button class="review-choice" id="addNote">Add note</button>`;root.prepend(panel);
    const activity=document.createElement("section");activity.className="detail-card desk-deal-activity";activity.innerHTML=`<div class="detail-card-title"><h2>Recent activity</h2></div><ul class="desk-activity">${(d.workflow.activity||[]).map(a=>`<li><strong>${e(a.title)}</strong><p>${e(a.detail)}</p></li>`).join("")||"<li>No activity recorded yet.</li>"}</ul>`;root.append(activity);
  };
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;
    if(b.dataset.deskPage)global.showPage(b.dataset.deskPage);
    if(b.dataset.deskDeal)global.openDeal(b.dataset.deskDeal);
    if(b.dataset.deskFilter){dealFilter=b.dataset.deskFilter;register();document.querySelector(`[data-desk-filter="${dealFilter}"]`).focus();}
    if(b.hasAttribute('data-start-pitch')){global.MandateStartPitch();}
  });
  document.addEventListener('input',event=>{if(event.target.id==='deskDealSearch'){dealQuery=event.target.value;document.getElementById('deskDealResults').innerHTML=dealResults();}if(event.target.id==='deskLenderSearch'){lenderQuery=event.target.value;document.getElementById('deskLenderResults').innerHTML=lenderResults();}});
})(window);
