import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {openDatabase} from '../server/db.js';
import {seed,thirtyProfile} from '../server/seed.js';
import {Workspace} from '../server/service.js';
import {createApp} from '../server/app.js';
import {extractCSV,legacyAnalysis,legacyFixtures} from '../server/analysis.js';
let db,svc,u,other,dealId,runId,server,base,cookie,otherCookie,documentId,reportId;
const org='ORG-DEMO-001';
async function mutation(action,body={},key=randomUUID(),who=u,deal=dealId){const d=await svc.workspace(who,deal);const b={version:d.deal.version,...body};return svc.mutation(who,key,{action,deal,...b},tx=>svc.action(tx,who,deal,action,b));}
async function request(url,body,session=cookie){const response=await fetch(base+'/api'+url,{headers:{Origin:base,Cookie:session||'','Content-Type':'application/json','Idempotency-Key':randomUUID()},...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)})});const data=await response.json();return {response,data};}
before(async()=>{db=await openDatabase({directory:':memory:',url:null});await db.migrate();await seed(db,{allow:true});svc=new Workspace(db);u=(await db.admin(tx=>tx.query('SELECT * FROM users WHERE organisation_id=$1 ORDER BY id',[org]))).rows[0];other=(await db.admin(tx=>tx.query("SELECT * FROM users WHERE organisation_id='ORG-DEMO-002'"))).rows[0];const c=await svc.mutation(u,randomUUID(),{},tx=>svc.create(tx,u,{deal_name:'Test persistent acquisition',profile:thirtyProfile()}));dealId=c.id;await mutation('confirm');
 server=createApp(db,{origin:'http://127.0.0.1:4311'}).listen(4311,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:4311';let login=await request('/login',{user_id:u.id});cookie=login.response.headers.get('set-cookie').split(';')[0];login=await request('/login',{user_id:other.id});otherCookie=login.response.headers.get('set-cookie').split(';')[0];});
after(async()=>{if(server)await new Promise(r=>server.close(r));if(db)await db.close();});
test('fixtures preserve Southern NZ$8m, five original scores/statuses and chronological mandate versions',async()=>{const w=await svc.workspace(u,'DEAL-SOUTHERN-001');assert.equal(w.deal.profile.funding.amount,8e6);assert.equal(w.deal.profile.financials.ebitda.amount,54e5);assert.equal(w.deal_matches.length,5);assert.equal(new Set(w.deal_matches.map(m=>m.status)).size,5);assert.deepEqual(w.match_results.map(r=>r.result.score).sort((a,b)=>b-a),[94,89,84,79,74]);const bad=await db.admin(tx=>tx.query('SELECT r.id FROM match_results r JOIN matching_runs mr ON mr.id=r.run_id JOIN provider_mandates pm ON pm.id=r.mandate_id AND pm.organisation_id=r.organisation_id WHERE pm.effective_from>mr.created_at'));assert.equal(bad.rows.length,0);assert.equal((await seed(db,{allow:true})).alreadySeeded,true);});
test('save exactly five returned providers atomically and idempotently',async()=>{const original=svc.providers;svc.providers=async tx=>(await original.call(svc,tx)).filter(p=>p.id.startsWith('CP-CLUB-')).slice(0,5);try{runId=(await mutation('analyze')).id;}finally{svc.providers=original;}const d=await svc.workspace(u,dealId),body={version:d.deal.version,run_id:runId},key=randomUUID(),save=()=>svc.mutation(u,key,body,tx=>svc.action(tx,u,dealId,'save-matches',body));assert.deepEqual(await save(),await save());const w=await svc.workspace(u,dealId);assert.equal(w.deal_matches.length,5);assert.equal(w.deal_events.filter(e=>e.event_type==='PROVIDER_MATCHED').length,5);assert.equal(w.match_results.length,5);});
test('independent statuses persist and create exactly one status event with correct actor/previous state',async()=>{let w=await svc.workspace(u,dealId);const statuses=['CONTACTED','WAITING','INTERESTED','DECLINED','TERMS_RECEIVED'];for(let i=0;i<5;i++){const m=w.deal_matches[i];await mutation('provider',{match_id:m.id,match_version:m.version,status:statuses[i],decline_reason:i===3?'LEVERAGE_TOO_HIGH':null});}w=await svc.workspace(u,dealId);assert.equal(new Set(w.deal_matches.map(m=>m.status)).size,5);const es=w.deal_events.filter(e=>e.event_type==='STATUS_CHANGED');assert.equal(es.length,5);assert.ok(es.every(e=>e.previous_status==='NOT_CONTACTED'&&e.actor_user_id===u.id));const m=w.deal_matches[0];await mutation('provider',{match_id:m.id,match_version:m.version,status:m.status});assert.equal((await svc.workspace(u,dealId)).deal_events.filter(e=>e.event_type==='STATUS_CHANGED').length,5);assert.equal(w.deal_matches.find(m=>m.status==='DECLINED').decline_reason,'LEVERAGE_TOO_HIGH');});
test('notes and dates survive a fresh authenticated session, with organisation inferred from session',async()=>{let w=await svc.workspace(u,dealId);const m=w.deal_matches[0];await mutation('provider',{match_id:m.id,match_version:m.version,next_follow_up_at:'2026-12-01T20:00:00Z',follow_up_note:'Call after board meeting',note:'Private broker note'});await mutation('note',{note_text:'Deal-only confidential note'});const login=await request('/login',{user_id:u.id});const fresh=login.response.headers.get('set-cookie').split(';')[0];const {response,data}=await request('/deals/'+dealId,undefined,fresh);assert.equal(response.status,200);assert.equal(data.deal_notes.length,2);assert.equal(data.deal_matches[0].follow_up_note,'Call after board meeting');assert.ok(data.deal_matches[0].next_follow_up_at);for(let i=1;i<data.deal_events.length;i++)assert.ok(new Date(data.deal_events[i-1].occurred_at)>=new Date(data.deal_events[i].occurred_at));});
test('stale shared edits are rejected and failed compound writes leave no partial event',async()=>{let w=await svc.workspace(u,dealId),m=w.deal_matches[0];await assert.rejects(()=>mutation('provider',{match_id:m.id,match_version:999,status:'CLOSED'}),/changed/);const count=w.deal_events.length;await assert.rejects(()=>mutation('provider',{match_id:m.id,match_version:m.version,status:'CLOSED',assigned_user_id:other.id}),/organisation/);w=await svc.workspace(u,dealId);assert.equal(w.deal_events.length,count);assert.notEqual(w.deal_matches[0].status,'CLOSED');});
test('rematching preserves original results, relationship activity and independent statuses',async()=>{const old=await svc.workspace(u,dealId);const r=await mutation('analyze');await mutation('save-matches',{run_id:r.id});const w=await svc.workspace(u,dealId);assert.equal(w.deal_matches.length,16);for(const m of old.deal_matches){const now=w.deal_matches.find(x=>x.id===m.id);assert.equal(now.status,m.status);assert.equal(now.original_result_id,m.original_result_id);assert.notEqual(now.latest_result_id,m.latest_result_id);}assert.equal(w.deal_notes.length,old.deal_notes.length);});
test('mandate update cannot rewrite historical score/snapshot and marks package input stale',async()=>{const w=await svc.workspace(u,dealId),p=w.providers.find(p=>p.id.startsWith('CP-CLUB-')),before=JSON.stringify(w.match_results);await db.tenant(u,tx=>tx.query('INSERT INTO provider_mandates(id,organisation_id,provider_id,effective_from,data) VALUES($1,$2,$3,$4,$5)',[randomUUID(),org,p.id,new Date(),JSON.stringify({...p.mandate.data,participationMax:5e6})]));assert.equal(JSON.stringify((await svc.workspace(u,dealId)).match_results),before);await assert.rejects(()=>mutation('package',{run_id:w.matching_runs.toSorted((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0].id}),/mandates changed/);});
test('package scenarios, preferred option and received terms persist without becoming funding',async()=>{const run=await mutation('analyze');await mutation('save-matches',{run_id:run.id});const scenario=await mutation('package',{run_id:run.id,name:'Validated NZ$30m options'});let w=await svc.workspace(u,dealId);const p=w.packages.find(p=>p.id===scenario.id);assert.ok(p.snapshot.alternatives.length);await mutation('choose-package',{package_id:p.id,alternative:0,reason:'Documented proposal for broker review'});w=await svc.workspace(u,dealId);assert.equal(w.deal.preferred_package_id,p.id);assert.equal(w.coverage.commitment,0);assert.equal(w.coverage.funding,0);const m=w.deal_matches.find(m=>m.provider_id==='CP-SOLO-DEMO');const terms=await mutation('funding',{match_id:m.id,facility_id:'main',kind:'terms',state:'indicative',amount:30e6,data:{source:'Fictional term letter',rate:'9.5% fixed',fees:'1% upfront',conditions:'Credit approval'}});await mutation('choose-terms',{record_id:terms.id,reason:'Sufficient amount; confirm conditions'});await mutation('funding',{match_id:m.id,facility_id:'main',kind:'commitment',state:'conditional',amount:30e6,data:{source:'Fictional conditional commitment'}});w=await svc.workspace(u,dealId);assert.equal(w.deal.preferred_terms_id,terms.id);assert.equal(w.coverage.conditional,3e9);assert.equal(w.coverage.commitment,0);assert.equal(w.coverage.funding,0);assert.notEqual(w.deal.overall_stage,'funded');await assert.rejects(()=>mutation('funding',{match_id:m.id,facility_id:'main',kind:'commitment',state:'active',amount:30e6,data:{source:'Duplicate'}}),/Revise/);const old=w.funding_records.find(r=>r.kind==='commitment');await mutation('funding',{match_id:m.id,facility_id:'main',kind:'commitment',state:'active',amount:30e6,supersedes_id:old.id,data:{source:'Conditions satisfied; fictional evidence'}});await mutation('funding',{match_id:m.id,facility_id:'main',kind:'funding',state:'funded',amount:6e6,data:{source:'First fictional drawdown received'}});w=await svc.workspace(u,dealId);assert.equal(w.coverage.commitment,3e9);assert.equal(w.coverage.conditional,0);assert.equal(w.coverage.funding,6e8);assert.equal(w.funding_records.length,4);});
test('closing tasks require completion evidence and preserve meaningful events',async()=>{const task=await mutation('task',{title:'Obtain valuation',assigned_user_id:u.id,due_at:'2026-12-01T20:00:00Z'});let w=await svc.workspace(u,dealId);const t=w.tasks.find(t=>t.id===task.id);await assert.rejects(()=>mutation('task',{id:t.id,task_version:t.version,title:t.title,completed:true}),/evidence/);await mutation('task',{id:t.id,task_version:t.version,title:t.title,completed:true,evidence:'Fictional signed valuation received'});w=await svc.workspace(u,dealId);assert.equal(w.tasks[0].completed,true);assert.equal(w.deal_events.filter(e=>e.event_type==='TASK_UPDATED').length,2);});
test('document parser reuses original CSV adapter; uploaded source is private and conflicts require review',async()=>{const text='field,value,currency,period_end\ncompany.name,Test Manufacturing,,\nfunding.amount,30000000,NZD,\nfinancials.ebitda,10000000,NZD,2026-03-31\n';assert.ok(extractCSV(text).length>=2);await mutation('upload',{files:[{name:'borrower.csv',content:text}]});const w=await svc.workspace(u,dealId);documentId=w.documents.at(-1).id;assert.equal(w.documents[0].content,undefined);assert.notEqual(w.deal.confirmed_version,w.deal.profile_version);assert.ok(w.packages.every(p=>p.profile_version!==w.deal.profile_version));await assert.rejects(()=>mutation('analyze'),/Confirm/);});
test('shareable reports exclude broker notes, provider history and nested internal profile fields',async()=>{let w=await svc.workspace(u,dealId);const result=w.match_results[0];const r=await mutation('report',{result_id:result.id,audience:'shareable'});reportId=r.id;const response=await request('/reports/'+r.id);assert.equal(response.response.status,200);assert.equal(response.data.snapshot.history,undefined);assert.equal(response.data.snapshot.result.history_profile,undefined);assert.ok(!JSON.stringify(response.data).includes('Private broker note'));assert.ok(!JSON.stringify(response.data).includes('Deal-only confidential'));const internal=await mutation('report',{result_id:result.id,audience:'internal'});const internalResult=await request('/reports/'+internal.id);const all=await svc.bootstrap(u);assert.equal(internalResult.data.snapshot.history.matched,all.deal_matches.filter(m=>m.provider_id===result.provider_id&&m.deal_id!==dealId).length);});
test('saved provider PDF downloads through the authenticated tenant route',async()=>{const headers={Cookie:cookie},response=await fetch(base+'/api/reports/'+reportId+'.pdf',{headers});assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/application\/pdf/);const bytes=Buffer.from(await response.arrayBuffer());assert.ok(bytes.subarray(0,8).equals(Buffer.from('%PDF-1.4')));const otherResponse=await fetch(base+'/api/reports/'+reportId+'.pdf',{headers:{Cookie:otherCookie}});assert.equal(otherResponse.status,404);});
test('RLS with normal mandate_app role protects every tenant table and immutable history',async()=>{const tables=['deals','documents','matching_runs','match_results','deal_matches','deal_events','deal_notes','packages','funding_records','reports','source_records','profile_versions'];for(const table of tables){const rows=await db.tenant(other,tx=>tx.query('SELECT * FROM '+table+' WHERE organisation_id=$1',[org]));assert.equal(rows.rows.length,0,table);}await assert.rejects(()=>db.tenant(other,tx=>tx.query("INSERT INTO deal_notes(id,organisation_id,deal_id,user_id,note_text) VALUES('attack',$1,$2,$3,'attack')",[org,dealId,u.id])),/row-level security/);await assert.rejects(()=>db.tenant(u,tx=>tx.query('UPDATE deal_events SET metadata=$1 WHERE deal_id=$2',['{}',dealId])),/permission denied/);await assert.rejects(()=>db.tenant(u,tx=>tx.query('DELETE FROM deal_events WHERE deal_id=$1',[dealId])),/permission denied/);const result=await db.tenant(other,tx=>tx.query('UPDATE deals SET deal_name=$1 WHERE id=$2',['attack',dealId]));assert.equal(result.affectedRows,0);});
test('HTTP authentication and tenant boundaries deny read/write/download/report/aggregate access',async()=>{assert.equal((await request('/bootstrap',undefined,'')).response.status,401);const b=await request('/bootstrap',undefined,otherCookie);assert.ok(b.data.deals.every(d=>d.organisation_id===other.organisation_id));for(const url of ['/deals/'+dealId,'/documents/'+documentId,'/reports/'+reportId,'/providers/CP-CLUB-1/history'])assert.equal((await request(url,undefined,otherCookie)).response.status,404,url);assert.equal((await request('/deals/'+dealId+'/note',{version:1,note_text:'attack',organisation_id:org},otherCookie)).response.status,404);const r=await fetch(base+'/api/deals',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);});
test('legacy matching still produces its original illustrative comparisons and no invented score',()=>{const ds=legacyFixtures();assert.ok(ds.length>=3);const a=legacyAnalysis(ds[0]);assert.ok(a.summary);assert.equal(a.lenderComparisons.length,3);assert.ok(a.lenderComparisons.every(r=>r.score===undefined));});
test('production rejects demo authentication',()=>assert.throws(()=>createApp(db,{authMode:'demo',production:true}),/cannot run in production/));
test('file-backed database survives close and reopen',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'mandate-persist-'));let local;try{local=await openDatabase({directory:dir,url:null});await local.migrate();await local.admin(tx=>tx.query("INSERT INTO organisations(id,name) VALUES('persist','Saved brokerage')"));await local.close();local=await openDatabase({directory:dir,url:null});assert.equal((await local.admin(tx=>tx.query("SELECT name FROM organisations WHERE id='persist'"))).rows[0].name,'Saved brokerage');}finally{if(local)await local.close();await rm(dir,{recursive:true,force:true});}});

test('clearing contact and follow-up dates persists without erasing recorded contact history',async()=>{
 let w=await svc.workspace(u,dealId),m=w.deal_matches.find(m=>m.status==='CONTACTED');
 const contacts=w.deal_events.filter(e=>e.event_type==='PROVIDER_CONTACTED').length;
 await mutation('provider',{match_id:m.id,match_version:m.version,last_contacted_at:null,next_follow_up_at:null,follow_up_note:''});
 w=await svc.workspace(u,dealId);m=w.deal_matches.find(x=>x.id===m.id);
 assert.equal(m.last_contacted_at,null);assert.equal(m.next_follow_up_at,null);
 assert.equal(w.deal_events.filter(e=>e.event_type==='PROVIDER_CONTACTED').length,contacts);
 assert.ok(w.deal_events.some(e=>e.event_type==='CONTACT_DATE_CHANGED'&&e.metadata.next===null));
});
test('expired or withdrawn transaction evidence invalidates proposals and cannot silently be reused',async()=>{
 const created=await svc.mutation(u,randomUUID(),{},tx=>svc.create(tx,u,{deal_name:'Participation expiry test',profile:thirtyProfile()}));
 const invoke=(a,b={})=>mutation(a,b,randomUUID(),u,created.id);
 await invoke('confirm');const run=await invoke('analyze');await invoke('save-matches',{run_id:run.id});const scenario=await invoke('package',{run_id:run.id});
 let w=await svc.workspace(u,created.id),m=w.deal_matches.find(m=>m.provider_id==='CP-SOLO-DEMO');
 const expired=await invoke('funding',{match_id:m.id,facility_id:'main',kind:'terms',state:'indicative',amount:30e6,expires_at:'2020-01-01T00:00:00Z',data:{source:'Expired fictional terms'}});
 w=await svc.workspace(u,created.id);assert.equal(w.participation_issues.length,1);
 await assert.rejects(()=>invoke('choose-package',{package_id:scenario.id,alternative:0,reason:'Old proposal'}),/expired/);
 const refreshed=await invoke('package',{run_id:run.id});w=await svc.workspace(u,created.id);
 assert.ok(w.packages.find(p=>p.id===refreshed.id).snapshot.alternatives.every(a=>a.allocations.every(x=>x.provider_id!==m.provider_id)));
 const renewed=await invoke('funding',{match_id:m.id,facility_id:'main',kind:'terms',state:'indicative',amount:30e6,supersedes_id:expired.id,data:{source:'Renewed fictional terms'}});
 assert.equal((await svc.workspace(u,created.id)).participation_issues.length,0);
 await invoke('funding',{match_id:m.id,facility_id:'main',kind:'terms',state:'withdrawn',amount:30e6,supersedes_id:renewed.id,data:{source:'Written withdrawal'}});
 assert.match((await svc.workspace(u,created.id)).participation_issues[0].reason,/withdrawn/);
});
test('actual commitments cannot double count the facility and received funding cannot expire',async()=>{
 const w=await svc.workspace(u,dealId),m=w.deal_matches.find(m=>m.provider_id.startsWith('CP-CLUB-'));
 await assert.rejects(()=>mutation('funding',{match_id:m.id,facility_id:'main',kind:'commitment',state:'active',amount:6e6,data:{source:'Duplicate economic capacity'}}),/exceeds this facility/);
 await assert.rejects(()=>mutation('funding',{match_id:m.id,facility_id:'main',kind:'funding',state:'funded',amoun