import { readFileSync, readdirSync } from 'node:fs';
import { parse } from 'csv-parse/sync';
import { id } from './domain.js';
import { Workspace } from './service.js';
const root=new URL('../MODEL/prototype/synthetic-data/reference-tables/',import.meta.url);
const list=v=>(v||'').split(';').map(x=>x.trim()).filter(Boolean),number=v=>v===''||v==null?null:Number(v);
export function thirtyProfile(){return {synthetic:true,company:{name:'Aotearoa Manufacturing Group — fictional',industry:'Manufacturing',location:'Hamilton, New Zealand'},funding:{amount:30000000,currency:'NZD',purpose:'Acquisition',purposes:['acquisition'],termMonths:36,security:['GSA'],type:'term_loan',targetBasis:'facility_limits',rolesConfirmed:false},financials:{annualRevenue:{amount:65000000,periodEnd:'2026-03-31',currency:'NZD'},ebitda:{amount:12000000,periodEnd:'2026-03-31',currency:'NZD'}},documents:[],review:{fields:{},conflicts:[],confirmedFields:[],proposedValues:{}},ratios:{leverage:2.5,leverageType:'gross_post_transaction_debt_to_EBITDA'}};}
export function packageProvider(i,max=6000000){return {id:'CP-CLUB-'+i,name:['Rimu','Totara','Manuka','Nikau','Pohutukawa','Rata','Puriri'][i-1]+' Demonstration Credit',data:{synthetic:true},mandate:{id:'MAN-CLUB-'+i,effective_from:'2026-01-01',data:{synthetic:true,currency:'NZD',sectors:['Manufacturing'],purposes:['acquisition','growth_capital'],security:['GSA'],facilityTypes:['term_loan'],minTerm:12,maxTerm:60,participationMin:1000000,participationMax:max,providerLimit:max,amountScope:'participation',availableCapital:max,capacityAsAt:new Date().toISOString(),coLend:true,canLead:i===1,securityGroup:'synthetic-shared-first-ranking',source:'Explicit fictional participation scenario; not a real provider mandate'}}};}
export async function seed(db,{allow=false}={}){
 if(!allow||process.env.NODE_ENV==='production')throw new Error('Seeding requires explicit synthetic mode and is disabled in production.');
 const tables={};for(const name of readdirSync(root))if(name.endsWith('.csv')){try{tables[name.slice(0,-4)]=parse(readFileSync(new URL(name,root),'utf8'),{columns:true,skip_empty_lines:true,bom:true});}catch(e){throw new Error(name+': '+e.message);}}
 return db.admin(async tx=>{
  if((await tx.query("SELECT id FROM organisations WHERE id='ORG-DEMO-001'")).rows.length)return {alreadySeeded:true};
  const org='ORG-DEMO-001',svc=new Workspace(db);
  await tx.query('INSERT INTO organisations(id,name) VALUES($1,$2),($3,$4)',[org,'Jasper Finance · fictional','ORG-DEMO-002','Other Brokerage · isolation example']);
  for(const u of tables.users)await tx.query('INSERT INTO users(id,organisation_id,name,email) VALUES($1,$2,$3,$4)',[u.user_id,org,u.name,u.email]);
  await tx.query("INSERT INTO users(id,organisation_id,name,email) VALUES('USR-OTHER-001','ORG-DEMO-002','Casey Example','casey@example.invalid')");
  const actor={id:tables.users[0].user_id,organisation_id:org};
  for(const p of tables.capital_providers)await tx.query('INSERT INTO capital_providers(id,organisation_id,name,data) VALUES($1,$2,$3,$4)',[p.provider_id,org,p.name,JSON.stringify(p)]);
  const mandates={};
  for(const r of tables.provider_mandates){const m={currency:r.currency,sectors:list(r.sectors),excludedSectors:list(r.excluded_sectors),purposes:list(r.financing_purposes),security:list(r.accepted_security),minDeal:number(r.min_deal_size),maxDeal:number(r.max_deal_size),minTerm:number(r.min_term_months),maxTerm:number(r.max_term_months),minEbitda:number(r.min_ebitda),maxLeverage:number(r.max_leverage),leverageType:null,amountScope:'unknown',amountScopeEvidence:'Legacy min/max deal size has no documented participation or facility scope; verify before use',participationMin:null,participationMax:null,availableCapital:number(r.available_capital),source:r.source_note,synthetic:true,legacy:r};mandates[r.mandate_id]=m;
   await tx.query('INSERT INTO provider_mandates(id,organisation_id,provider_id,effective_from,data) VALUES($1,$2,$3,$4,$5)',[r.mandate_id,org,r.provider_id,r.effective_from,JSON.stringify(m)]);
   // Separate fictional historical version; never backdate a real verified mandate.
   await tx.query('INSERT INTO provider_mandates(id,organisation_id,provider_id,effective_from,data) VALUES($1,$2,$3,$4,$5)',[r.mandate_id+'-HISTORICAL',org,r.provider_id,'2024-01-01',JSON.stringify({...m,source:'Synthetic historical version reconstructed for fixture consistency; not verified historical terms'})]);
  }
  for(let i=1;i<=7;i++){const p=packageProvider(i);await tx.query('INSERT INTO capital_providers(id,organisation_id,name,data) VALUES($1,$2,$3,$4)',[p.id,org,p.name,JSON.stringify(p.data)]);await tx.query('INSERT INTO provider_mandates(id,organisation_id,provider_id,effective_from,data) VALUES($1,$2,$3,$4,$5)',[p.mandate.id,org,p.id,p.mandate.effective_from,JSON.stringify(p.mandate.data)]);}
  const solo=packageProvider(1,30000000);solo.id='CP-SOLO-DEMO';solo.name='Single Facility Demonstration Fund';solo.mandate.id='MAN-SOLO-DEMO';solo.mandate.data.coLend=false;solo.mandate.data.participationMin=20000000;
  await tx.query('INSERT INTO capital_providers(id,organisation_id,name,data) VALUES($1,$2,$3,$4)',[solo.id,org,solo.name,JSON.stringify(solo.data)]);await tx.query('INSERT INTO provider_mandates(id,organisation_id,provider_id,effective_from,data) VALUES($1,$2,$3,$4,$5)',[solo.mandate.id,org,solo.id,solo.mandate.effective_from,JSON.stringify(solo.mandate.data)]);
  const profiles={};
  for(const r of tables.deals){const c=tables.companies.find(c=>c.company_id===r.company_id),periods=tables.financial_periods.filter(f=>f.company_id===r.company_id),fin=periods.filter(f=>!f.period_type.includes('forecast')).sort((a,b)=>b.period_end.localeCompare(a.period_end))[0]||{};
   const fs=tables.facility_requests.filter(f=>f.deal_id===r.deal_id).map(f=>({id:f.request_id,name:f.tranche_name,amount:number(f.amount),currency:'NZD',termMonths:number(f.term_months),type:f.facility_type.toLowerCase().includes('revolv')?'revolver':'term_loan',security:list(f.security_type),purposes:r.purpose_category==='capex;working_capital'?[f.tranche_name.includes('Equipment')?'capex':'working_capital']:list(r.purpose_category)}));
   const profile={synthetic:true,company:{name:c?.legal_name||r.borrower_alias,industry:c?.industry||null,location:r.location,alias:r.borrower_alias,source:c},funding:{amount:number(r.amount_requested),currency:r.currency,purpose:r.purpose_detail,purposes:list(r.purpose_category),termMonths:number(r.desired_term_months),security:r.deal_id==='DEAL-KOWHAI-001'?['Equipment','GSA']:['GSA','plant and equipment'],type:'term_loan',targetBasis:'facility_limits',desiredCloseDate:r.desired_close_date},financials:{annualRevenue:{amount:number(fin.revenue),currency:r.currency,periodEnd:fin.period_end},ebitda:{amount:r.deal_id==='DEAL-SOUTHERN-001'?5400000:number(fin.ebitda),currency:r.currency,periodEnd:fin.period_end,basis:r.ebitda_basis},periods},ratios:{leverage:number(r.leverage_value),leverageType:r.leverage_type,existingDebt:number(r.existing_debt),unrestrictedCash:number(r.cash_unrestricted)},facilities:fs.length?fs:undefined,documents:[],review:{fields:{},conflicts:[],confirmedFields:[],proposedValues:{}}};profiles[r.deal_id]=profile;
   const stage=r.overall_stage==='matching_review'?'adviser_review':r.overall_stage;
   const firstMatch=tables.deal_matches.filter(m=>m.deal_id===r.deal_id).map(m=>m.matched_at).sort()[0];const created=firstMatch&&firstMatch<r.created_at?firstMatch:r.created_at;
   await tx.query('INSERT INTO deals(id,organisation_id,created_by_user_id,assigned_user_id,deal_name,overall_stage,profile,confirmed_version,created_at) VALUES($1,$2,$3,$3,$4,$5,$6,1,$7)',[r.deal_id,org,actor.id,r.deal_name,stage,JSON.stringify(profile),created]);await svc.snapshot(tx,actor,r.deal_id,1,profile);
   for(const [kind,rows]of Object.entries(tables)){if(['deal_matches','deal_events','deal_notes','deals','users','organisations','provider_mandates','capital_providers'].includes(kind))continue;for(const row of rows){if(row.deal_id===r.deal_id||row.company_id===r.company_id){const key=Object.values(row)[0];await tx.query('INSERT INTO source_records(id,organisation_id,deal_id,kind,data) VALUES($1,$2,$3,$4,$5)',[String(key),org,r.deal_id,kind,JSON.stringify(row)]);}}}
  }
  for(const dealId of new Set(tables.deal_matches.map(m=>m.deal_id))){const run='SEED-RUN-'+dealId,ms=tables.deal_matches.filter(m=>m.deal_id===dealId),date=ms[0].matched_at;await tx.query('INSERT INTO matching_runs(id,organisation_id,deal_id,profile_version,snapshot,engine_version,saved_at,created_at) VALUES($1,$2,$3,1,$4,$5,$6,$6)',[run,org,dealId,JSON.stringify({profile:profiles[dealId]}),'hand-authored synthetic history',date]);
   for(const r of ms){const rid='RESULT-'+r.deal_match_id,mid=r.provider_mandate_id+(date<'2026-01-01'?'-HISTORICAL':'');const p=tables.capital_providers.find(p=>p.provider_id===r.provider_id);const result={provider_id:r.provider_id,provider_name:p.name,mandate_id:mid,mandate_snapshot:{id:mid,data:mandates[r.provider_mandate_id]},score:number(r.match_score),score_scale:r.score_scale||null,score_source:r.score_source,checks:[],reasons:list(r.match_reasons),outcome:'needs_check',history_profile:profiles[dealId]};await tx.query('INSERT INTO match_results(id,organisation_id,run_id,provider_id,mandate_id,result) VALUES($1,$2,$3,$4,$5,$6)',[rid,org,run,r.provider_id,mid,JSON.stringify(result)]);
    await tx.query('INSERT INTO deal_matches(id,organisation_id,deal_id,provider_id,original_result_id,latest_result_id,status,decline_reason,last_contacted_at,next_follow_up_at,assigned_user_id,matched_at) VALUES($1,$2,$3,$4,$5,$5,$6,$7,$8,$9,$10,$11)',[r.deal_match_id,org,dealId,r.provider_id,rid,r.status,r.decline_reason||null,r.last_contacted_at||null,r.next_follow_up_at||null,r.assigned_user,r.matched_at]);
   }
  }
  for(const e of tables.deal_events){const metadata={fixture_text:e.metadata};if(e.metadata.startsWith('reason='))metadata.decline_reason=e.metadata.slice(7);await tx.query('INSERT INTO deal_events(id,organisation_id,deal_id,deal_match_id,provider_id,actor_user_id,event_type,previous_status,new_status,metadata,occurred_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)',[e.event_id,org,e.deal_id,e.deal_match_id||null,e.provider_id||null,e.actor_user_id,e.event_type,e.previous_status||null,e.new_status||null,JSON.stringify(metadata),e.created_at]);}
  for(const n of tables.deal_notes)await tx.query('INSERT INTO deal_notes(id,organisation_id,deal_id,deal_match_id,user_id,note_text,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[n.note_id,org,n.deal_id,n.deal_match_id||null,n.author_user_id,n.note_text,n.created_at]);
  // An explicit older closed example supplies real event inputs for history calculations.
  const olderId='DEAL-OLDER-CLOSED',olderProfile={...thirtyProfile(),funding:{...thirtyProfile().funding,amount:6000000}},olderProvider=tables.capital_providers[0],olderMandate=tables.provider_mandates.find(m=>m.provider_id===olderProvider.provider_id),olderRun='RUN-OLDER-CLOSED',olderResult='RESULT-OLDER-CLOSED',olderMatch='MATCH-OLDER-CLOSED';
  await tx.query("INSERT INTO deals(id,organisation_id,created_by_user_id,assigned_user_id,deal_name,overall_stage,profile,confirmed_version,created_at) VALUES($1,$2,$3,$3,'Previous manufacturing expansion · fictional','closed',$4,1,'2025-06-01')",[olderId,org,actor.id,JSON.stringify(olderProfile)]);await svc.snapshot(tx,actor,olderId,1,olderProfile);
  await tx.query("INSERT INTO matching_runs(id,organisation_id,deal_id,profile_version,snapshot,engine_version,saved_at,created_at) VALUES($1,$2,$3,1,$4,'explicit fictional history','2025-06-01','2025-06-01')",[olderRun,org,olderId,JSON.stringify({profile:olderProfile})]);
  await tx.query('INSERT INTO match_results(id,organisation_id,run_id,provider_id,mandate_id,result) VALUES($1,$2,$3,$4,$5,$6)',[olderResult,org,olderRun,olderProvider.provider_id,olderMandate.mandate_id+'-HISTORICAL',JSON.stringify({provider_id:olderProvider.provider_id,provider_name:olderProvider.name,mandate_id:olderMandate.mandate_id+'-HISTORICAL',mandate_snapshot:{id:olderMandate.mandate_id+'-HISTORICAL',data:mandates[olderMandate.mandate_id]},score:null,score_source:'No score recorded in fictional history',reasons:[],checks:[],outcome:'needs_check',history_profile:olderProfile})]);
  await tx.query("INSERT INTO deal_matches(id,organisation_id,deal_id,provider_id,original_result_id,latest_result_id,status,last_contacted_at,assigned_user_id,matched_at) VALUES($1,$2,$3,$4,$5,$5,'CLOSED','2025-06-02',$6,'2025-06-01')",[olderMatch,org,olderId,olderProvider.provider_id,olderResult,actor.id]);
  let previous='NOT_CONTACTED';for(const [status,time]of [['CONTACTED','2025-06-02T00:00:00Z'],['INTERESTED','2025-06-04T00:00:00Z'],['TERMS_RECEIVED','2025-06-08T00:00:00Z'],['CLOSED','2025-06-28T00:00:00Z']]){await svc.event(tx,actor,olderId,'STATUS_CHANGED',{synthetic:true},{id:olderMatch,provider_id:olderProvider.provider_id},previous,status,time);previous=status;}
  const p=thirtyProfile();await tx.query("INSERT INTO deals(id,organisation_id,created_by_user_id,assigned_user_id,deal_name,profile,confirmed_version,overall_stage) VALUES('DEAL-30M', $1,$2,$2,'Aotearoa Manufacturing Acquisition',$3,1,'ready_to_send')",[org,actor.id,JSON.stringify(p)]);await svc.snapshot(tx,actor,'DEAL-30M',1,p);await svc.event(tx,actor,'DEAL-30M','DEAL_CREATED',{synthetic:true});
  await tx.query("INSERT INTO deals(id,organisation_id,created_by_user_id,assigned_user_id,deal_name,profile) VALUES('DEAL-OTHER','ORG-DEMO-002','USR-OTHER-001','USR-OTHER-001','Private isolation example',$1)",[JSON.stringify({...p,company:{...p.company,name:'Other organisation borrower'}})]);
  return {seeded:true,deals:7,providers:16};
 });
}
