"use client";

import { useState } from "react";

import { SummaryMarkdown } from "@/components/app/SummaryMarkdown";
import { Card } from "@/components/ui/Card";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { Textarea } from "@/components/ui/Field";
import { generateSummaryAction, updateSummaryAction } from "@/lib/actions/applications";
import type { DealSummary } from "@/lib/types";

export function DealSummaryCard({
  applicationId,
  summary,
  canExport,
}: {
  applicationId: string;
  summary: DealSummary | null;
  canExport: boolean;
}) {
  const [editing, setEditing] = useState(false);

  return (
    <Card className="p-7">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="font-display text-xl text-graphite">Deal analysis & lender options</h2>
          {summary && (
            <p className="mt-1 text-xs text-grey">
              {summary.ai_generated ? "Generated by AI" : "Generated from form fields"} ·{" "}
              {new Date(summary.updated_at).toLocaleString("en-NZ", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}
            </p>
          )}
        </div>
        <div className="flex shrink-0 gap-2">
          {summary && !editing && (
            <button
              onClick={() => setEditing(true)}
              className="rounded-[var(--radius-control)] border border-rule-strong px-3 py-1.5 text-[12.5px] font-medium text-graphite-soft hover:border-graphite"
            >
              Edit
            </button>
          )}
          {summary && canExport && (
            <a
              href={`/api/applications/${applicationId}/summary/export`}
              className="rounded-[var(--radius-control)] border border-rule-strong px-3 py-1.5 text-[12.5px] font-medium text-graphite-soft hover:border-graphite"
            >
              Export PDF
            </a>
          )}
          <form action={generateSummaryAction}>
            <input type="hidden" name="application_id" value={applicationId} />
            <SubmitButton pendingLabel="Generating…" className="!bg-graphite !px-3.5 !py-1.5 !text-[12.5px]">
              {summary ? "Run analysis again" : "Analyze deal & prepare PDF"}
            </SubmitButton>
          </form>
        </div>
      </div>

      <div className="mt-6">
        {!summary ? (
          <p className="text-[14px] text-grey">
            Upload the deal folder, then analyze it to create a lender-ready summary and downloadable PDF.
            Synthetic CSV examples add fictional lender comparisons, package options, and reasons providers were excluded.
          </p>
        ) : editing ? (
          <form
            action={async (formData) => {
              await updateSummaryAction(formData);
              setEditing(false);
            }}
          >
            <input type="hidden" name="application_id" value={applicationId} />
            <Textarea name="content" defaultValue={summary.content} rows={18} className="font-mono text-[13px]" />
            <div className="mt-3 flex gap-2">
              <SubmitButton pendingLabel="Saving…">Save changes</SubmitButton>
              <button
                type="button"
                onClick={() => setEditing(false)}
                className="rounded-[var(--radius-control)] border border-rule-strong px-4 py-2 text-sm font-medium text-graphite-soft hover:border-graphite"
              >
                Cancel
              </button>
            </div>
          </form>
        ) : (
          <SummaryMarkdown content={summary.content} />
        )}
      </div>
    </Card>
  );
}
