"""Rebuild Mandate's outlined SVG identity from the licensed Manrope source.

Requires fonttools and brotli. Run from the repository root.
Source fonts and their OFL licences live alongside the generated assets.
"""
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.basePen import BasePen
import json

ROOT = Path('MODEL/prototype/assets/brand')
TEAL, GLASS, FLAX = '#244947', '#BFE0D4', '#E4D28B'
symbol = f'<rect width="48" height="48" rx="15" fill="{TEAL}"/><path d="M14 16h9a7 7 0 0 1 0 14h-2m13 2h-9a7 7 0 0 1 0-14h2" fill="none" stroke="{GLASS}" stroke-width="3" stroke-linecap="round"/><g fill="{FLAX}"><circle cx="13" cy="16" r="3"/><circle cx="35" cy="32" r="3"/></g>'

def svg(name, width, height, content, title):
    (ROOT / name).write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" role="img" aria-label="{title}"><title>{title}</title>{content}</svg>\n', encoding='utf-8')

font = instantiateVariableFont(TTFont(ROOT/'fonts/manrope.ttf'), {'wght':750})
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
scale = 36/font['head'].unitsPerEm
pen = SVGPathPen(glyphs)
x = 0
for char in 'Mandate':
    glyph = glyphs[cmap[ord(char)]]
    glyph.draw(TransformPen(pen, (scale,0,0,-scale,x,36)))
    x += glyph.width*scale - .65
path = pen.getCommands()
width = round(x+1,2)
svg('mandate-symbol.svg',48,48,symbol,'Mandate connected symbol')
svg('mandate-app-icon.svg',48,48,symbol,'Mandate app icon')
# Pixel-aligned simplified mark remains readable in a browser's 16px tab.
svg('mandate-favicon.svg',32,32,f'<rect width="32" height="32" rx="9" fill="{TEAL}"/><path d="M9 10h6a5 5 0 0 1 0 10h-2m10 2h-6a5 5 0 0 1 0-10h2" fill="none" stroke="{GLASS}" stroke-width="2.5" stroke-linecap="round"/><g fill="{FLAX}"><circle cx="9" cy="10" r="2"/><circle cx="23" cy="22" r="2"/></g>','Mandate')
for suffix,fill in [('',TEAL),('-reverse',GLASS)]:
    svg(f'mandate-wordmark{suffix}.svg',width,48,f'<path fill="{fill}" d="{path}"/>','Mandate')
    svg(f'mandate-lockup{suffix}.svg',width+62,48,symbol+f'<path transform="translate(62)" fill="{fill}" d="{path}"/>','Mandate')

# Use the same outlined lettering in the local PDF header, without a font dependency.
class PDFPen(BasePen):
    def __init__(self): super().__init__(glyphs); self.ops=[]
    def _moveTo(self,p): self.ops.append(f'{p[0]:.3f} {p[1]:.3f} m')
    def _lineTo(self,p): self.ops.append(f'{p[0]:.3f} {p[1]:.3f} l')
    def _curveToOne(self,a,b,c): self.ops.append(' '.join(f'{n:.3f}' for p in (a,b,c) for n in p)+' c')
    def _closePath(self): self.ops.append('h')
pdf = PDFPen(); x=73; scale=22/font['head'].unitsPerEm
for char in 'Mandate':
    glyph=glyphs[cmap[ord(char)]]
    glyph.draw(TransformPen(pdf,(scale,0,0,scale,x,802)))
    x+=glyph.width*scale-.4
mark = ('q .5 0 0 -.5 44 824 cm '
        '0.1412 0.2863 0.2784 rg '
        '15 0 m 33 0 l 41.284 0 48 6.716 48 15 c 48 33 l '
        '48 41.284 41.284 48 33 48 c 15 48 l 6.716 48 0 41.284 0 33 c '
        '0 15 l 0 6.716 6.716 0 15 0 c f '
        '0.749 0.878 0.831 RG 3 w 1 J '
        '14 16 m 23 16 l 26.866 16 30 19.134 30 23 c '
        '30 26.866 26.866 30 23 30 c 21 30 l S '
        '34 32 m 25 32 l 21.134 32 18 28.866 18 25 c '
        '18 21.134 21.134 18 25 18 c 27 18 l S '
        '0.894 0.824 0.545 rg ')
for cx,cy in [(13,16),(35,32)]:
    k=1.657
    mark += (f'{cx+3} {cy} m {cx+3} {cy+k} {cx+k} {cy+3} {cx} {cy+3} c '
             f'{cx-k} {cy+3} {cx-3} {cy+k} {cx-3} {cy} c '
             f'{cx-3} {cy-k} {cx-k} {cy-3} {cx} {cy-3} c '
             f'{cx+k} {cy-3} {cx+3} {cy-k} {cx+3} {cy} c f ')
ops=mark+'Q q 0.1412 0.2863 0.2784 rg '+ ' '.join(pdf.ops)+' f Q'
(ROOT/'brand-pdf.js').write_text('// Generated by tools/build-brand-assets.py; outlined Manrope wordmark.\nwindow.MandateBrandPDF='+json.dumps(ops)+';\n',encoding='utf-8')
for name in ['manrope','dm-sans']:
    f=TTFont(ROOT/f'fonts/{name}.ttf');f.flavor='woff2';f.save(ROOT/f'fonts/{name}.woff2')
print('Created outlined logos, icons, PDF lettering and local WOFF2 fonts.')
