-- Mandate — initial schema.
--
-- Written in the subset of SQL that both PostgreSQL (production) and SQLite
-- (zero-config local dev, via node:sqlite) accept, so there is exactly one
-- schema to maintain:
--
--   * ids are TEXT (uuid v4 generated by the app, not the database)
--   * money is INTEGER cents — never floats
--   * booleans are INTEGER 0/1
--   * timestamps are TEXT ISO-8601 UTC strings, written by the app
--   * JSON columns are TEXT holding a JSON document, parsed by the app
--
-- See lib/db.ts for the thin driver that speaks to whichever engine is configured.

CREATE TABLE IF NOT EXISTS users (
  id                     TEXT PRIMARY KEY,
  email                  TEXT NOT NULL UNIQUE,
  name                   TEXT NOT NULL DEFAULT '',
  password_hash          TEXT,
  firm_name              TEXT NOT NULL DEFAULT '',
  logo_url               TEXT,
  plan                   TEXT NOT NULL DEFAULT 'trial',
  subscription_status    TEXT NOT NULL DEFAULT 'trialing',
  trial_ends_at          TEXT,
  stripe_customer_id     TEXT,
  stripe_subscription_id TEXT,
  created_at             TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions (user_id);

-- One row per loan application. `is_sample` marks the seeded demo deals so
-- the UI can label them and so a fresh adviser account can tell them apart
-- from their own work at a glance.
CREATE TABLE IF NOT EXISTS applications (
  id                  TEXT PRIMARY KEY,
  adviser_id          TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  client_name         TEXT NOT NULL,
  loan_amount_cents   INTEGER NOT NULL DEFAULT 0,
  purpose             TEXT NOT NULL DEFAULT 'commercial_property',
  location            TEXT NOT NULL DEFAULT '',
  property_value_cents INTEGER,
  pre_sales_pct       REAL,
  loan_term_months    INTEGER,
  notes               TEXT NOT NULL DEFAULT '',
  status              TEXT NOT NULL DEFAULT 'draft',
  is_sample           INTEGER NOT NULL DEFAULT 0,
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS applications_adviser_idx ON applications (adviser_id);
CREATE INDEX IF NOT EXISTS applications_status_idx ON applications (status);

CREATE TABLE IF NOT EXISTS application_documents (
  id             TEXT PRIMARY KEY,
  application_id TEXT NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
  filename       TEXT NOT NULL,
  storage_path   TEXT NOT NULL,
  mime_type      TEXT NOT NULL DEFAULT 'application/pdf',
  size_bytes     INTEGER NOT NULL DEFAULT 0,
  extracted_text TEXT,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS documents_application_idx ON application_documents (application_id);

CREATE TABLE IF NOT EXISTS deal_summaries (
  id             TEXT PRIMARY KEY,
  application_id TEXT NOT NULL UNIQUE REFERENCES applications (id) ON DELETE CASCADE,
  content        TEXT NOT NULL DEFAULT '',
  lvr_pct        REAL,
  ai_generated   INTEGER NOT NULL DEFAULT 0,
  generated_at   TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

-- Global directory of non-bank lenders. Not adviser-scoped.
CREATE TABLE IF NOT EXISTS lenders (
  id                    TEXT PRIMARY KEY,
  name                  TEXT NOT NULL,
  min_loan_cents        INTEGER NOT NULL,
  max_loan_cents        INTEGER NOT NULL,
  max_lvr_pct           REAL NOT NULL,
  regions               TEXT NOT NULL DEFAULT '[]',
  loan_types            TEXT NOT NULL DEFAULT '[]',
  pre_sales_requirement TEXT NOT NULL DEFAULT 'either',
  contact_email         TEXT NOT NULL DEFAULT '',
  notes                 TEXT NOT NULL DEFAULT ''
);

-- One row per (application, lender) the matcher has surfaced or the adviser
-- has manually tracked. match_score/reasons are recomputed on demand; stage
-- is the adviser's own record of contact and is never overwritten.
CREATE TABLE IF NOT EXISTS application_lenders (
  id             TEXT PRIMARY KEY,
  application_id TEXT NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
  lender_id      TEXT NOT NULL REFERENCES lenders (id) ON DELETE CASCADE,
  match_score    INTEGER NOT NULL DEFAULT 0,
  match_reasons  TEXT NOT NULL DEFAULT '[]',
  stage          TEXT NOT NULL DEFAULT 'matched',
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  UNIQUE (application_id, lender_id)
);
CREATE INDEX IF NOT EXISTS application_lenders_app_idx ON application_lenders (application_id);

CREATE TABLE IF NOT EXISTS application_events (
  id             TEXT PRIMARY KEY,
  application_id TEXT NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
  type           TEXT NOT NULL DEFAULT 'note',
  message        TEXT NOT NULL DEFAULT '',
  from_status    TEXT,
  to_status      TEXT,
  due_at         TEXT,
  done_at        TEXT,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS events_application_idx ON application_events (application_id);
